apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  frontend
  template:
    metadata:
      name: myapp
      labels:
        app: frontend
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80