apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    app:  frontend
spec:
  replicas: 2
  template:
    metadata:
      name: myapp
      labels:
        app: frontend
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80