apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: NodePort # Type may be 1. NodePort 2. ClusterIP 3. LoadBalancer.
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
